#### 注意：在处理多进程的时候，需要使用共享Array。如果不是用共享Array，则赋值会出错。本代码为测试版本。

In [1]:
# coding: utf-8 
import os
import numpy as np
import multiprocessing
from multiprocessing import Array
import time

In [2]:
def listdir_nohidden(path):
    return filter( lambda f: not f.startswith('.'), os.listdir(path))  

In [3]:
#获取目标文件夹的路径
# filedir = '/media/jerry/Sexxy/aa-alexnet-output/'
# 处理好的conv5的aa系数
filedir = '/media/jerry/Sexxy/aa-alexnet-tmp/data/'
#获取当前文件夹中的文件名称列表  
dir_1=list(listdir_nohidden(filedir))

# print dir_1
# print type(dir_1)
# print len(dir_1)

In [3]:
# conv5_coeff_4d = np.zeros(256* 8* 1000* 1728)
# conv5_coeff_4d = conv5_coeff_4d.reshape(256, 8, 1000, 1728)

conv5_coeff_3d = np.zeros(256* 1000* 1728)
conv5_coeff_3d = conv5_coeff_3d.reshape(256, 1000, 1728)

conv5_coeff_2d = np.zeros(256*  1728)
conv5_coeff_2d = conv5_coeff_2d.reshape(256, 1728)

# print conv5_coeff_4d.shape
print conv5_coeff_3d.shape
print conv5_coeff_2d.shape

(256, 1000, 1728)
(256, 1728)


In [51]:
# ## Loop Test Line:
# i = 0

# d1 = dir_1[i].split(".", 1)  ## 分割符，分割次数 '0' , 'txt'
# kernel_num = int(d1[0])
# print kernel_num

# base = filedir + dir_1[i]
# b = np.loadtxt(base, dtype=np.float32)
# print b.shape

# c_3d = b.reshape(8, 1000, 1728)

# conv5_coeff_4d[kernel_num] = c_3d

# # print c_3d.shape ## (8, 1000, 1728)

# c_3d = np.abs(c_3d) ## 取绝对值

# d_2d = np.mean(c_3d, 0) ## 按照 8 求平均
# # print d_2d.shape ## (1000, 1728)
# conv5_coeff_3d[kernel_num] = d_2d ## 存入3维数组对应的kernel
# # np.savetxt('/home/jerry/c5_2d.txt', d_2d)

# e_1d= np.mean(d_2d, 0) ## (1728,)
# # print e_1d.shape
# conv5_coeff_2d[kernel_num] = e_1d
# w5_coeff = e_1d.reshape(192,3,3)

In [52]:
# test_d = np.load('/home/jerry/c5_2d.npy')
# print test_d

In [69]:
def worker(num1, num2):

    for i in range(num1, num2):
        print i
        base = filedir + dir_1[i]
        d1 = dir_1[i].split(".", 1)  ## 分割符，分割次数
        kernel_num = int(d1[0])
        
    #     print base
    #     print d1
        print 'kernel_num: ', kernel_num


        b = np.loadtxt(base, dtype=np.float32)
        print b.shape

        c_3d = b.reshape(8, 1000, 1728)
    #     conv5_coeff_4d[kernel_num] = c_3d

        # print c_3d.shape ## (8, 1000, 1728)

        c_3d = np.abs(c_3d) ## 取绝对值

        d_2d = np.mean(c_3d, 0) ## 按照 8 求平均 (1000, 1728)
#         print d_2d
        print ' '
        conv5_coeff_3d[kernel_num] = d_2d ## 存入3维数组对应的kernel
        # np.savetxt('/home/jerry/c5_2d.txt', d_2d)
#         print conv5_coeff_3d[kernel_num]
        
        e_1d= np.mean(d_2d, 0) ## (1728,)
        conv5_coeff_2d[kernel_num] = e_1d
        print 'i: ', i, 'Done'

In [70]:
def multi_process():
    # p1 = multiprocessing.Process(target = worker, args = (0,64,))
    # p2 = multiprocessing.Process(target = worker, args = (64,128,))
    # p3 = multiprocessing.Process(target = worker, args = (128,192,))
    # p4 = multiprocessing.Process(target = worker, args = (192,256,))

    p1 = multiprocessing.Process(target = worker, args = (0,1,))
    # p2 = multiprocessing.Process(target = worker, args = (64,65,))
    # p3 = multiprocessing.Process(target = worker, args = (128,129,))
    # p4 = multiprocessing.Process(target = worker, args = (192,193,))


    p1.start()
    # p2.start()
    # p3.start()
    # p4.start()

    # print("The number of CPU is:" + str(multiprocessing.cpu_count()))
    # for p in multiprocessing.active_children():
    #     print("child   p.name:" + p.name + "\tp.id" + str(p.pid))
    # print "END!!!!!!!!!!!!!!!!!"


In [73]:
multi_process()
if (conv5_coeff_3d.all() == 0): print 1
print conv5_coeff_3d[0]

0
kernel_num:  0
1
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(13824000,)
 
i:  0 Done


1
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [47]:
# (256, 8, 1000, 1728)
# (256, 1000, 1728)
# (256, 1728)

# np.save('/home/jerry/data-alexnet/npy/c5_4d.npy', conv5_coeff_4d)
np.save('/home/jerry/data-alexnet/npy/c5_3d.npy', conv5_coeff_3d)
np.save('/home/jerry/data-alexnet/npy/c5_2d.npy', conv5_coeff_2d)


In [ ]:
# str = "Line1-abcdef \nLine2-abc \nLine4-abcd";
# print str.split( );
# print str.split(' ', 1 );

In [20]:
i = 0
base = filedir + dir_1[i]
d1 = dir_1[i].split(".", 1)  ## 分割符，分割次数
kernel_num = int(d1[0])
#     print base
#     print d1
#     print kernel_num


b = np.loadtxt(base, dtype=np.float32)
print b.shape

(13824000,)


In [25]:
c_3d = b.reshape(8, 1000, 1728)
#     conv5_coeff_4d[kernel_num] = c_3d
# print c_3d

# print c_3d.shape ## (8, 1000, 1728)

c_3d = np.abs(c_3d) ## 取绝对值

print kernel_num

d_2d = np.mean(c_3d, 0) ## 按照 8 求平均 (1000, 1728)
print d_2d


conv5_coeff_3d[kernel_num] = d_2d ## 存入3维数组对应的kernel
# np.savetxt('/home/jerry/c5_2d.txt', d_2d)
print conv5_coeff_3d[0]

e_1d= np.mean(d_2d, 0) ## (1728,)
conv5_coeff_2d[kernel_num] = e_1d

0
[[1.44528826e-07 2.36466335e-07 2.36815040e-07 ... 1.23985913e-07
  1.07867475e-08 7.12413879e-08]
 [7.80914746e-08 1.99844067e-07 3.59917351e-07 ... 1.74817728e-07
  3.64177630e-08 1.85189919e-07]
 [1.81916263e-07 1.51214067e-07 1.96629586e-07 ... 1.40744930e-07
  1.18653070e-08 3.18679092e-08]
 ...
 [7.87133274e-08 1.22093240e-07 1.85087785e-07 ... 5.46669483e-08
  1.36085463e-08 7.29748777e-08]
 [8.79909337e-08 2.72080172e-07 2.64818198e-07 ... 8.19374009e-08
  2.05165023e-08 1.25887823e-07]
 [8.96744510e-08 1.37044580e-07 1.95254586e-07 ... 8.39494447e-08
  3.15372759e-08 8.01873625e-08]]
[[1.44528826e-07 2.36466335e-07 2.36815040e-07 ... 1.23985913e-07
  1.07867475e-08 7.12413879e-08]
 [7.80914746e-08 1.99844067e-07 3.59917351e-07 ... 1.74817728e-07
  3.64177630e-08 1.85189919e-07]
 [1.81916263e-07 1.51214067e-07 1.96629586e-07 ... 1.40744930e-07
  1.18653070e-08 3.18679092e-08]
 ...
 [7.87133274e-08 1.22093240e-07 1.85087785e-07 ... 5.46669483e-08
  1.36085463e-08 7.29748777e-0

In [38]:
t_dir = './npy/c5_2d.npy'

t_1 = np.load(t_dir)

In [39]:
t_1.shape

(256, 1728)

In [40]:
t_1[0]

array([1.98067212e-07, 2.22565717e-07, 3.29617137e-07, ...,
       1.67751949e-07, 3.37968196e-08, 1.01581051e-07])